"""add profile fields to users

Revision ID: 0802ba6abbf2
Revises: 
Create Date: 2026-07-10 19:45:57.765977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
#from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0802ba6abbf2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('skills', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('github_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('portfolio_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'portfolio_url')
    op.drop_column('users', 'linkedin_url')
    op.drop_column('users', 'github_url')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'about_me')
    op.drop_column('users', 'year')
    op.drop_column('users', 'department')
    # ### end Alembic commands ###
