"""version 2 database

Revision ID: c151ade72610
Revises: d09b78c1abc5
Create Date: 2026-07-13 21:32:06.969519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c151ade72610'
down_revision: Union[str, Sequence[str], None] = 'd09b78c1abc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('applications', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.create_foreign_key(None, 'applications', 'users', ['reviewed_by'], ['id'])
    op.add_column('team_members', sa.Column('role', sa.String(length=30), nullable=False))
    op.alter_column('team_members', 'joined_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('profile_completion', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('users', 'register_number',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False))
    op.alter_column('users', 'register_number',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'profile_completion')
    op.drop_column('users', 'password')
    op.alter_column('team_members', 'joined_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_column('team_members', 'role')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.alter_column('applications', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_column('applications', 'updated_at')
    op.drop_column('applications', 'reviewed_at')
    op.drop_column('applications', 'reviewed_by')
    # ### end Alembic commands ###
