"""upgrade team model v2

Revision ID: d09b78c1abc5
Revises: 0802ba6abbf2
Create Date: 2026-07-13 21:23:18.794754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd09b78c1abc5'
down_revision: Union[str, Sequence[str], None] = '0802ba6abbf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('teams', sa.Column('hashtags', sa.Text(), nullable=True))
    op.add_column('teams', sa.Column('banner_image', sa.String(length=255), nullable=True))
    op.add_column('teams', sa.Column('event_date', sa.DateTime(), nullable=True))
    op.add_column('teams', sa.Column('registration_deadline', sa.DateTime(), nullable=True))
    op.add_column('teams', sa.Column('status', sa.String(length=30), nullable=False))
    op.add_column('teams', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('teams', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('teams', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_column('teams', 'updated_at')
    op.drop_column('teams', 'status')
    op.drop_column('teams', 'registration_deadline')
    op.drop_column('teams', 'event_date')
    op.drop_column('teams', 'banner_image')
    op.drop_column('teams', 'hashtags')
    op.drop_column('teams', 'category')
    # ### end Alembic commands ###
